DemoSite/Controllers/HomeController.cs
using System.Collections.Generic;
using DemoSite.Models;
using System.Web.Mvc;

namespace DemoSite.Controllers
{
	public class HomeController : Controller
	{
		[HttpGet]
	    public ViewResult Index()
		{
		    /*
            * Assign page title with view bag, create a model and pass to view
            */
		    ViewBag.title = "Welcome";
		    List<Models.AdModel> modelList = Domain.ContentCreation.CreationUtilties.MakeJobAd();
		    return View(modelList);
		}

	    [HttpGet]
	    public ViewResult RegistrationForm()
	    {
	        /*
            * Assign page title with view bag
            */
	        ViewBag.title = "Registration";
	        return View();
	    }

	    [HttpPost]
	    public ViewResult RegistrationForm(RegModel registration)
	    {
            /*
            * Assign page title with view bag, check returned model is valid
            * if true pass model to completed view if false return to view
            */
	        ViewBag.title = "Registration required";
	        if (ModelState.IsValid)
	        {
	            return View("Completed", registration);
	        }
	        else
	        {
	            return View();
	        }
	    }

	    [HttpGet]
	    public ViewResult LoginForm()
	    {
	        /*
            * Assign page title with view bag
            */
	        ViewBag.title = "Login";
	        return View();
	    }

	    [HttpPost]
	    [ValidateAntiForgeryToken]
	    public ActionResult LoginForm(UserModel user)
	    {
	        /*
            * Check if model properties are set and then set session variable.
            * Allow session status to be passed between pages using tempData
            * Assign page title with view bag, check returned model is valid
            * if true pass model to secure view if false return to view
            */
	        ViewBag.title = "Login";
	        if (ModelState.IsValid)
	        {
	            if (!((user.Password != null) & (user.Email != null))) return View(user);
	            var UserList = new UserModel(){Password = "pass", Email = "demo@demo.com"};
	            Session["LogedUserID"] = UserList.Email.ToString();
	            TempData["UserID"] = Session["LogedUserID"];
	            //return RedirectToAction("Secure");
	            return Redirect(Url.RouteUrl(new { controller = "Home", action = "Secure" }) + "#anchor");
	        }
	        else
	        {
	            return View();
	        }
	    }

	    [HttpGet]
	    public ActionResult Completed()
	    {
	        /*
            * Assign page title with view bag
            */
	        ViewBag.title = "Thank you";
	        return View();
	    }

	    [HttpGet]
	    public ActionResult Secure()
	    {
	        /*
            * Assign page title with view bag
            * Check session status and return view
            * If navigate away then null TempData and force a re-login
            */
	        ViewBag.title = "Restricted Area";
	        if (Session["LogedUserID"] != null && TempData["UserID"] != null )
	        {
	            return View();
	        }
	        TempData["UserID"] = null;
	        return RedirectToAction("LoginForm", "Home");
	    }

	    [HttpGet]
	        /*
            * create a model and pass to partial model
            */
	    public ActionResult TeamPartial()
	    {
	        List<TeamModel> modelList = Domain.ContentCreation.CreationUtilties.MakeTeam();
	        return PartialView("Shared/_TeamPartial",modelList);
	    }
	}
}

DemoSite/Controllers/InterviewController.cs
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using DemoSite.Models;

namespace DemoSite.Controllers
{
    public class InterviewController : Controller
    {
        [HttpGet]
        public ViewResult Index()
        {
            /*
            * Assign page title with view bag
            */
            ViewBag.title = "Interview request";
            return View();
        }

        [HttpGet]
        public ViewResult InterviewForm()
        {
            /*
            * Assign page title with view bag
            */
            ViewBag.title = "Interview request";
            return View();
        }

        [HttpPost]
        public ActionResult InterviewForm(VacancyApplyModel vacancy)
        {
            /*
            * Assign page title with view bag
            * Check model is correct or act accordingly
            */
            ViewBag.title = "Interview request";
            if (ModelState.IsValid)
            {
                ViewBag.title = "Interview form";
                return View("ThankYou", vacancy);
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ViewResult ThankYou()
        {
            /*
            * Assign page title with view bag
            */
            ViewBag.title = "Thankyou";
            return View();
        }
    }
}

DemoSite/Views/Home/Completed.cshtml
@model DemoSite.Models.RegModel

<div>
    <h1>Congratualation, @Model.Name!!!</h1>
        <p>Your Registration has been Successfully completed.</p>
    </div>

DemoSite/Views/Home/Index.cshtml
@using DemoSite.Domain.ContentCreation
@using DemoSite.Models
﻿@model List<AdModel>

<div class="container-fluid">
    <!-- -------------------------------------------Circle scroll row--------------------------------------------------- -->
    <div class="row">
        <div id="circle">
            <a id="misc" href="#misc">
                <i class="fa fa-arrow-down fa-3x" aria-hidden="true"></i>
            </a>
        </div>
    </div>
    <!-- -----------------------------------------------Header row------------------------------------------------------- -->
    <div class="row">
        <div class="HomeHeader col p-5" style="margin-top: -48px;  min-height: 400px; width: 100%; background-color: ghostwhite">
            <h2 class="h2 text-center">
                Welcome to [Company name]...
                <small class="text-muted"><span class="red">[Industry]</span> focused provider</small>
            </h2>
            <br/>
            <p>
                With <span class="red">[number of years experience]</span> working within <span class="red">[Sector]</span>, we take specialist recruitment to the next level. We provide a full recruitment cycle covering all roles within <span class="red">[sector areas/location]</span>
            </p>
            <br/>
            <p>Whether you're looking for a new opportunity now, or would like to speak with the right people to help you when you decide the time is right then please get in touch for a confidential chat.</p>
        </div>
    </div>
    <!-- -----------------------------------------------Vacancy row------------------------------------------------------- -->
    <div class="row">
        <div class="HomeVacancies scrolltarget" style="min-height: 400px; width: 100%; background-color: #292b2c">

            <h2 class="h2 text-center py-5" style="color: ghostwhite;">
                Vacancies
            </h2>

            <div id="card-list" class="row px-5 pb-5">
                @{
                    foreach (var getter in Model)
                    {
                        <div class="col-lg-4 col-md-6 my-1">
                            <div class="card">
                                <div class="card-header">
                                    @getter.Title
                                </div>
                                <div class="card-block">
                                    <h4 class="card-title">Vacancy Details:</h4>
                                    <p class="card-text">@getter.Description</p>
                                    <a href="@Url.Action("FindOutMore", "Vacancies", new {@Title = getter.Title, @Author = getter.Author, @Description = getter.Description})" class="btn btn-primary pull-right">Apply</a>
                                </div>
                                <div class="card-footer text-muted">
                                    <p style="font-size: 0.7em; font-style: italic">Submitted by: @getter.Author closing date: @getter.EndAd.ToShortDateString()</p>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
    <!-- ----------------------------------------------Social media row------------------------------------------------------ -->
    <div class="row">
        <div class="HomeSocialMedia col pb-5 px-5" style="padding-top: 60px; min-height: 400px; width: 100%; background-color: ghostwhite">
            <h2 class="h2 text-center">
                Social media
            </h2>
            <br/>
            <p>
                Nulla ut sollicitudin ipsum, eget feugiat tortor. Sed eget eleifend odio. Sed sit amet pretium urna. Nullam non nisl mi.
            </p>
            <p>
                Sed feugiat tincidunt massa id vulputate. Morbi rutrum purus suscipit, pretium felis vel, vulputate velit. Etiam sed urna dolor. Sed consequat quam est, et sagittis purus eleifend sed. Sed a.
            </p>
            <br/>
            <div class="text-center">
                <a href="#"> <i class="fa fa-facebook-official fa-5x" aria-hidden="true"></i></a>
                <a href="#"> <i class="fa fa-twitter-square fa-5x" aria-hidden="true"></i></a>
                <a href="#"> <i class="fa fa-instagram fa-5x" aria-hidden="true"></i></a>
                <a href="#"> <i class="fa fa-linkedin-square fa-5x" aria-hidden="true"></i></a>
            </div>
        </div>
    </div>
    <!-- -----------------------------------------------Team row------------------------------------------------------- -->
    <div class="row">
        <div class="HomeTeam" style="min-height: 400px; width: 100%; background-color: #292b2c">

            <h2 class="h2 text-center py-5" style="color: ghostwhite;">
                Meet the team
            </h2>
            @Html.Partial("~/Views/Home/Shared/_TeamPartial.cshtml", CreationUtilties.MakeTeam())
        </div>
    </div>
    <!-- ----------------------------------------------Interview row------------------------------------------------------ -->
    <div class="row">
        <div class="Interview col pb-5 px-5" style="padding-top: 60px; min-height: 400px; width: 100%;  background-color: ghostwhite">
            <h2 class="h2 text-center">
                Interview
            </h2>
            <br/>
            <p>
                Nulla ut sollicitudin ipsum, eget feugiat tortor. Sed eget eleifend odio. Sed sit amet pretium urna. Nullam non nisl mi.
            </p>
            <p>
                Sed feugiat tincidunt massa id vulputate. Morbi rutrum purus suscipit, pretium felis vel, vulputate velit. Etiam sed urna dolor. Sed consequat quam est, et sagittis purus eleifend sed. Sed a.
            </p>
            <br/>
            <div class="card">
                <h3 class="card-header">Interview request</h3>
                <div class="card-block">
                    <h4 class="card-title">Want a professional boost to your job search?</h4>
                    <p class="card-text">Quisque blandit interdum tortor, vitae mollis purus. Proin condimentum facilisis dolor, quis ornare est ultrices a. Sed ut elementum est. Vestibulum quis tellus sed dui scelerisque tincidunt in id urna.</p>
                    @Html.ActionLink("Book an interview", "InterviewForm", "Interview", null, null, "anchor", null, new {@class = "btn btn-primary pull-right"})
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/Content/JS/centreItHomePage.js"></script>
}

DemoSite/Views/Home/LoginForm.cshtml
@model DemoSite.Models.UserModel
<div class="container">
    <div class="row pb-5">
        <div class="col">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-signin">
                    <h2 class="form-signin-heading" id="anchor">Login</h2>
                    <div>
                        @Html.LabelFor(x => x.Email, new {@class = "sr-only"})
                        @Html.TextBoxFor(x => x.Email, new {id = "inputEmail", @class = "form-control", placeholder = "Email address"})
                        @Html.ValidationMessageFor(x => x.Email, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.LabelFor(x => x.Password, new {@class = "sr-only"})
                        @Html.PasswordFor(x => x.Password, new {id = "inputPassword", @class = "form-control", placeholder = "Password"})
                        @Html.ValidationMessageFor(x => x.Password, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Submit"/>
                    </div>
                </div>
            }
            <p class="text-muted text-center">email: demo@demo.com password: pass</p>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/Content/JS/ResponsiveValidation.js"></script>
}

DemoSite/Views/Home/RegistrationForm.cshtml
@model DemoSite.Models.RegModel

<div class="container">
    <div class="row pb-5">
        <div class="col">
            @using (Html.BeginForm())
            {
                <div class="form-signin">
                    <h2 class="form-signin-heading"  id="anchor">Register</h2>
                    <div>
                        @Html.LabelFor(x => x.Name, new {@class = "sr-only"})
                        @Html.TextBoxFor(x => x.Name, new {id = "inputName", @class = "form-control", placeholder = "Name"})
                        @Html.ValidationMessageFor(x => x.Name, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.LabelFor(x => x.Address, new {@class = "sr-only"})
                        @Html.TextBoxFor(x => x.Address, new {id = "inputAddress", @class = "form-control", placeholder = "Address"})
                        @Html.ValidationMessageFor(x => x.Address, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.LabelFor(x => x.Email, new {@class = "sr-only"})
                        @Html.TextBoxFor(x => x.Email, new {id = "inputEmail", @class = "form-control", placeholder = "Email"})
                        @Html.ValidationMessageFor(x => x.Email, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.LabelFor(x => x.Phone, new {@class = "sr-only"})
                        @Html.TextBoxFor(x => x.Phone, new {id = "inputPhone", @class = "form-control", placeholder = "Phone number"})
                        @Html.ValidationMessageFor(x => x.Phone, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Submit"/>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/Content/JS/ResponsiveValidation.js"></script>
}

DemoSite/Views/Home/Secure.cshtml
<div class="container">
    <div class="row">
        <div class="col">
            <h2 id="anchor">Secure section</h2>
        </div>
    </div>
    <div class="row" id="anchor">
        <div class="col pb-5">
            <p>Hello from your secure area</p>
            <p>Below is a link to the git repo of this site. If you'd link access send me a quick email.</p>
            <a href="https://fused19@bitbucket.org/fused19/recruitmentsitedemo.git">Git repo</a>
        </div>
    </div>
</div>